### ISSUE TITLE
Conda version of Biokit

### ISSUE THREAD

**Issue by Andyargueasae** [JLSteenwyk/BioKIT#1]
Hi!

I just wonder could the newest version of biokit also be uploaded in conda?

Cheers

**Comment by JLSteenwyk** [comment]
Hi @Andyargueasae,

Is the version on PyPi not sufficient? You can use this YAML file for your Snakemake workflow (assuming this ticket is related to your OrthoSNAP ticket).

best,

Jacob

**Comment by JLSteenwyk** [comment]
Hi,

It has been over a month, and I haven't heard any more updates. I assume the issue has been resolved, however, please feel free to reopen it if that is not the case.

best,

Jacob

**Comment by Andyargueasae** [comment]
Yes, it is working.
