### ISSUE TITLE
RSCU issue

### ISSUE THREAD

**Issue by jamiemcg** [JLSteenwyk/BioKIT#6]
Hi,

I'm noticing some inconsistencies with rscu results.

Here's an example sequence:
```
>seq
ATGCGTCTGTACTTGATTCTGTCAGCATCGATGGTCATCAGCTATTTTGTGACCTGTAACGCGGCTACGAGTTCCGATCA
GACCAAGCTCTCGAGAATGGAGCCATCACTCCTCGTCCACTCACTCGGTGCAGCACTGAACGTCGATGCCGTCGACAGAA
GATTTCTTCGAGAGCGAAAAGAAAGTATGGAAGAGCGAGGATATCATCTGACGCTAAAAGGGGAAGTAAAAGCATTGGCC
AAGAAAATCATTGCAGATTTCGACACGGCCGACGACGTGTACAAGAAGTGGAATGAGAACGGCCACTCGTTGAACAAAAT
CGCGAACTTGCTGAAAGTGTCGGAAAAGGAAAAATACGTACCGGTGTACAACGGCTATCTGGCCTACCTGAACAGGATAA
ATAGCTGA
```

And the `biokit rscu` output:

```
CGA	4.5
AGA	4.5
ACG	4.0
UGA	3.0
ACC	2.6667
CUG	2.4706
UCG	2.0
CCA	2.0
CCG	2.0
CAG	2.0
...
...
```

As an example codon, I think the RSCU of CGA should be 2.25?
3/(8/6)

Looking through the code, it looks like the `observed_sum` value is wrong as it is reset to 0 when a KeyError exception is thrown:

https://github.com/JLSteenwyk/BioKIT/blob/595a79d99234832014d66c6ced9a61c1a73c4f9d/biokit/services/coding_sequences/base.py#L54-L60

If I replace this with a pass statement, I get the expected result 2.25.

**Comment by JLSteenwyk** [comment]
Hi @jamiemcg,

Thank you so much for writing and using BioKIT.

I have updated the codebase following your suggestion (see version 1.1.3).

Thank you again for raising this issue and, even more so, finding the solution!

Please let me know if anything else comes up and potentially check out some of the [other software](https://jlsteenwyk.com/software.html) that we have developed!

All the best,

Jacob
